# Generated by Django 5.2 on 2025-05-20 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0004_author_remove_book_author_book_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=250)),
                ('bio', models.TextField(max_length=1000)),
                ('website', models.URLField(max_length=250)),
                ('author', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='my_first_app.author')),
            ],
        ),
    ]
