# Generated by Django 5.2 on 2025-05-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
