# Generated by Django 5.2 on 2025-05-31 16:25

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path, verbose_name='Product Photo'),
        ),
    ]
